# Extract Data from Becker's table

In [2]:
from numpy import genfromtxt, savetxt, where
from sys import exit
import numpy as np
import itertools

In [3]:
fname= 'EOS_becker.txt'
outname= 'EOS_plot_Bck.txt'

In [4]:
header1 = genfromtxt(fname, max_rows=1, dtype= 'str')
print(header1)

['Rho' 'T' 'P' 'U']


In [5]:
names= [ 'T', 'Rho', 'P']
num= []
for n in names:
    
    try:
        num.append(where(header1==n)[0][0])
    except ValueError:
        exit("The given name %s did not match any entry in header1. Valid values are %s" %(n, header1))
print("Done.", num)

Done. [1, 0, 2]


In [14]:
data =  genfromtxt(fname, skip_header=1, usecols=num)
#data= data[112::]

data[:,0]=np.log10(data[:,0])
data[:,1]=np.log10(data[:,1])
data[:,2]=np.log10(data[:,2])

data[:,2] += 10
#values=[-7., -6., -5., -4., -3., -2., -1., 0., 1., 2., 3.]
#data=np.array([])
#for n in range(len(data_brut[:,1])):
#    for v in values: 
#        if data_brut[n,1]==v:
#            #print(data_brut[n,1])
#            data=np.append(data,data_brut[n,:])
#a=len(data)//3
#data.shape=(a,3)
print(data)
form = " %1.6f  %+1.6f  %+1.6f"

hdr = "# Log T   Log Rho   Log P"
savetxt(outname, data, fmt=form, delimiter='  ', header=hdr, comments='')
len(np.unique(data[:,1]))

[[ 1.77815125 -7.52287875  1.87069184]
 [ 1.77815125 -7.39794001  1.99563046]
 [ 1.77815125 -7.30103     2.09254029]
 ...
 [ 7.          3.14612804 18.51500651]
 [ 7.          3.20411998 18.5901321 ]
 [ 7.          3.25527251 18.65738977]]


106