# Import section

In [7]:
from numpy import genfromtxt, savetxt, where
from sys import exit
import numpy as np
import itertools

# Defining file names
## output file name is the same with .dat extension instead of .data

In [8]:
fname   = "profile26.data"

#une chaine de caracteres est un tableau pour python ou chaque case est une lettre
#on peut donc utiliser les memes methodes que pour les tableaux
#ici on lui dit de garder les cases du tableau (i.e. les lettres) entre le début (rien à gauche du :, on aurait aussi pu mettre 0)
#et la deuxieme case en partant de la fin (d'ou le signe - qui lui indique de compter a partir de la fin), c'est a dire l'avant-derniere
#case (lettre), ce qui retire le a a la fin de .data
outname = "zmjup2"
print(fname, outname)

profile26.data zmjup2


# Opening file and getting header

In [9]:
#On recupere les 5 premiers lignes en premier (header) au cas ou t'en as besoin
#premier ligne avec les nombres. max_rows dit combien de lignes lire depuis le début.
#dype dit quel type de donnee on veut, ici une chaine de caracteres (pour les chaines de caracteres c'est obligatoire, pour le reste non)
header1 = genfromtxt(fname, max_rows=1, dtype='int')

#deuxieme ligne avec les noms. skip_header dit combien de ligne il ne faut pas lire depuis le debut du fichier.
header2 = genfromtxt(fname, max_rows=1, skip_header=1, dtype='str')

#troisieme ligne avec des nombres et un peu de texte (c'est pour ca que je le recupere en chaine de caracteres)
header3 = genfromtxt(fname, max_rows=1, skip_header=2, dtype='str')

#quatrieme ligne avec des nombres
header4 = genfromtxt(fname, max_rows=1, skip_header=3, dtype='int')

#cinquieme ligne avec des noms encore (j'ai mis 5 car il y a une ligne qui est sautee dans le fichier)
header5 = genfromtxt(fname, max_rows=1, skip_header=5, dtype='str')

# Checking everything is fine

In [10]:
#on peut les afficher pour verifier que ca a bien marche (le \n permet de revenir a la ligne)
print(header1, "\n\n", header2, "\n\n", header3, "\n\n", header4, "\n\n", header5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53] 

 ['model_number' 'num_zones' 'initial_mass' 'initial_z' 'star_age'
 'time_step' 'M_center' 'R_center' 'Teff' 'photosphere_L' 'photosphere_r'
 'center_eta' 'center_h1' 'center_he3' 'center_he4' 'center_c12'
 'center_n14' 'center_o16' 'center_ne20' 'star_mass' 'star_mdot'
 'star_mass_h1' 'star_mass_he3' 'star_mass_he4' 'star_mass_c12'
 'star_mass_n14' 'star_mass_o16' 'star_mass_ne20' 'he_core_mass'
 'c_core_mass' 'o_core_mass' 'si_core_mass' 'fe_core_mass'
 'neutron_rich_core_mass' 'tau10_mass' 'tau10_radius' 'tau100_mass'
 'tau100_radius' 'dynamic_time' 'kh_timescale' 'nuc_timescale'
 'power_nuc_burn' 'power_h_burn' 'power_he_burn' 'power_neu' 'burn_min1'
 'burn_min2' 'time_seconds' 'version_number' 'compiler' 'build'
 'MESA_SDK_version' 'date'] 

 ['300' '472' '1.0000000000000000E+000' '2.0000000000000000E-002'
 '4.90148449

# Getting data

## getting column numbers

Cette partie n'est pas obligatoire en soi, si tu sais quelle colonnes utiliser et leur position tu peux directement mettre dans num les numeros

In [11]:
#on cree une liste qui contient les noms de variable listees dans header5 qu'on veut garder
names = [ 'zone', 'logRho', 'logT']

#on va chercher dans header5 ou ils se trouvent pour savoir quel numero de colonne garder
#on cree une liste vide qu'on va remplir avec nos numero de colonnes
num = []

#on fait un essai (le try) pour chaque nom dans names
for n in names:
    try:
        
        #on cherche la premiere occurence (ici il n'y en a qu'une seule mais on sait jamais) parmis la liste dans header5 de la valeur contenue dans la
        #variable n.
        #Pour ce faire on utilise la fonction numpy where. Voici son fonctionnement. On lui donne en entree un array numpy (c'est ce qu'on a avec genfromtxt)
        #qui ne contient que des True ou des False, et elle nous dit ou sont les True.
        #L'astuce est donc de faire le header5==n qui va cree un array numpy avec des True partour ou ca vaut la valeur contenue dans n et des False partout
        #ailleurs ou c'est different. Ainsi where retournera bien l'endroit ou se trouve la valeur de n dans header5.
        #On rajoute le [0][0] a la fin car where retourne un array 2D (une matrice), donc on recupere le premier element (dans notre cas c'est le seul)
        num.append(where(header5==n)[0][0])
        
    #si ca plante parce qu'il n'y a pas le nom n dans header5 (parce qu'on l'a mal ecrit ou que la lecture du header n'a pas bien marchee par exemple)
    #on stoppe et on affiche un petit message d'erreur
    except ValueError:
        exit("The given name %s did not match any entry in header5. Valid values are %s" %(n, header5))
        
#Si ca a marche on le dit
print("Done.", num)

Done. [0, 2, 1]


# Writing new data into outputfile

In [12]:
#on refait comme pour le header mais on ne specifie pas le nombre de lignes qu'on veut lire
#Par contre on dit le nombre qu'on ne veut pas lire au debut. Pour cela on utilise le mot cle usecols et on
#lui donne une liste qui contient les numeros de colonne qu'on veut (donc num)
#Et surtout on specifie quels numero de colonnes on veut seulement lire
data = genfromtxt(fname, skip_header=6, usecols=num)
#data = itools.islice(data, 0, None, 2)
data = data[::2] 
print(data)



#on definit le format qu'on veut utiliser. f pour nombre reel, e pour notation scientifique, d pour entiers
#le format s'ecrit %a.bV ou a est le nombre de chiffres avant la virgule, b le nombre apres et V est le caractere (e, f, d, etc.) qui
#dit quel type de nombre on veut ecrire
form = " %3d          %+1.3f  %+1.3f"

#on definit le header (premier ligne qui va etre ecrite)
hdr = " K   Log D   log T"

#comme on veut deux colonnes logT logRho mais que data est constitué de deux lignes logT puis logRho (tu peux print data pour t'en convaincre),
#on fait la transposee
#data = data.T

#on utilise savetxt pour sauvegarder les donnes (le plus simple dans notre cas)
#je choisis pour delimiteur une tabulation entre chaque colonne (le \t)
#le header est celui donnepar hdr
#le format par fmt
#le comment correspond au caractere qui est rajoute devant la ligne du header (pour dire que c'est un commentaire et non des donnees),
#dans votre fichier il n'y en a pas donc j'ai mis une chaine de caracteres vide (le '')
savetxt(outname, data, fmt=form, delimiter='  ', header=hdr, comments='')

[[ 1.00000000e+00 -5.05848282e+00  3.09758409e+00]
 [ 3.00000000e+00 -5.05846806e+00  3.09758620e+00]
 [ 5.00000000e+00 -5.05843309e+00  3.09759120e+00]
 [ 7.00000000e+00 -5.05830102e+00  3.09761007e+00]
 [ 9.00000000e+00 -5.05795165e+00  3.09765999e+00]
 [ 1.10000000e+01 -5.05721513e+00  3.09776524e+00]
 [ 1.30000000e+01 -5.05547655e+00  3.09801389e+00]
 [ 1.50000000e+01 -5.04973857e+00  3.09883576e+00]
 [ 1.70000000e+01 -5.04036546e+00  3.10018237e+00]
 [ 1.90000000e+01 -5.01529173e+00  3.10380178e+00]
 [ 2.10000000e+01 -4.96814062e+00  3.11062283e+00]
 [ 2.30000000e+01 -4.92972459e+00  3.11613357e+00]
 [ 2.50000000e+01 -4.90087488e+00  3.12014423e+00]
 [ 2.70000000e+01 -4.86344793e+00  3.12520337e+00]
 [ 2.90000000e+01 -4.82899390e+00  3.12952140e+00]
 [ 3.10000000e+01 -4.80551100e+00  3.13228401e+00]
 [ 3.30000000e+01 -4.76059562e+00  3.13694674e+00]
 [ 3.50000000e+01 -4.71793259e+00  3.14013969e+00]
 [ 3.70000000e+01 -4.66922102e+00  3.14214085e+00]
 [ 3.90000000e+01 -4.63727757e+